### ISSUE TITLE
Not working for rustc?

### ISSUE THREAD

**Issue by dima74** [boringcactus/cargo-why#1]
Thank you for useful tool!

Looks like it doesn't work for [`rust-lang/rust`](https://github.com/rust-lang/rust):

```sh
git clone https://github.com/rust-lang/rust --recurse-submodules -j8
cd rust
cargo why winapi
```
results in:
```
Error: ErrorMessage { msg: "No dependency resolution root" }
```

**Comment by boringcactus** [comment]
The issue there is [rust's Cargo.toml](https://github.com/rust-lang/rust/blob/master/Cargo.toml) says it's a workspace with a lot of crates and no primary crate. I agree that cargo-why should handle workspaces properly, though.

**Comment by boringcactus** [comment]
Pushed version 0.2.0, which should work.

**Comment by dima74** [comment]
@boringcactus thank you, it works!
